FROM nginx:alpine

LABEL maintainer="贰拾壹 (https://github.com/er10yi)"


RUN rm -rf /usr/share/nginx/html/*

COPY .nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /usr/share/nginx/html

WORKDIR /usr/share/nginx/html

ENV TZ Asia/Shanghai